### PR TITLE
[Fix #3268] extensions autoload now correctly spawns extension processes

### LINKED ISSUE #3268: windows: Auto-load extensions crashes osquery
Currently using an `--extensions_autoload` value on windows will cause the client and daemon to crash. This is due to the child process which runs the extensions never being created. The child process is never created as we make use of a `#define pid_t unsigned long` as an attempt to emulate the Unix `pid_t` type, however `pid_t`s are signed, where as the Windows equivalent of `DWORD` is not.

### PR DESCRIPTION
**Pull request by poppyseedplehzr**
This addresses #3268 by ensuring that the initial checks of `isChildSane` for launching extensions _fails_, which ensures that the extension processes are launched on the first iteration through our `WatcherRunner::start` loop.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit c369dc8ce621c7487aaa5d8b8b7e9b2dc1d5c998 (Job results: [1543](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1543/)) failed one or more tests (**Windows**).

**Comment by arijabart** [comment]
Hi...

File: osquery/core/watcher.cpp [hunk 1]
```diff
@@ -361,7 +362,14 @@ Status WatcherRunner::isWatcherHealthy(const PlatformProcess& watcher,
 }
 
 QueryData WatcherRunner::getProcessRow(pid_t pid) const {
-  return SQL::selectAllFrom("processes", "pid", EQUALS, INTEGER(pid));
+  // On Windows, pid_t = DWORD, which is unsigned. However invalidity
+  // of processes is denoted by a pid_t of -1. We check for this
+  // by comparing the max value of DWORD, or ULONG_MAX
+  int p = pid;
+  if (isPlatform(PlatformType::TYPE_WINDOWS) && pid == ULONG_MAX) {
```
Comment (theopolis) [inline osquery/core/watcher.cpp]: Nit, could this be a ternary?

File: osquery/core/windows/process.cpp [hunk 2]
```diff
@@ -71,7 +71,8 @@ bool PlatformProcess::operator!=(const PlatformProcess& process) const {
 }
 
 int PlatformProcess::pid() const {
-  return static_cast<int>(::GetProcessId(id_));
+  auto pid = id_ == INVALID_HANDLE_VALUE ? -1 : GetProcessId(id_);
```
Comment (theopolis) [inline osquery/core/windows/process.cpp]: Nit, mind wrapping the expression in parens?

**Comment by osqueryer** [comment]
:no_good: The commit 296606e6f0e9e99a9c6389e0d767a13e3fbf38c4 (Job results: [1512](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1512/)) failed the code audit or documentation test.

**Comment by poppyseedplehzr** [comment]
Waiting on one of my VMs to verify this fix is working internally for us then I'll merge.

**Comment by osqueryer** [comment]
:-1: The commit ead05899716b80d89da07bdbdc5c67915a7e03a9 (Job results: [1552](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1552/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:-1: The commit ead05899716b80d89da07bdbdc5c67915a7e03a9 (Job results: [1553](https://jenkins.osquery.io/job/osqueryPullRequestWindows/1553/)) failed one or more tests (**Windows**).

**Comment by osqueryer** [comment]
:no_good: The commit 18f044f10587adb656579e3e6200be31973ab200 (Job results: [1519](https://jenkins.osquery.io/job/osqueryPullRequestAudit/1519/)) failed the code audit or documentation test.
