### PR TITLE
Fix gatekeeper table on macOS 15+

### LINKED ISSUE #8528: Displaying gatekeeper as enabled incorrectly
# Bug report

It seems that gatekeeper table is incorrectly displaying gatekeeper as enabled when it should be displayed as disabled. I can see in the code [here](https://github.com/osquery/osquery/blob/master/osquery/tables/system/darwin/gatekeeper.cpp#L82) that it is looking for the existance of the file `/var/db/SystemPolicy-prefs.plist` and if it doesn't exist it means that gatekeeper must be enabled. This is not true in my case, since gatekeeper is disabled and the file does not exist in my system.

### What operating system and version are you using?

```
+---------+--------+----------+
| version | build  | platform |
+---------+--------+----------+
| 15.2    | 24C101 | darwin   |
+---------+--------+----------+
```

### What version of osquery are you using?

```
+---------+
| version |
+---------+
| 5.14.1  |
+---------+

```
### What steps did you take to reproduce the issue?

1. Run the following command:
`spctl --status`
and got back:
`assessments disabled`

2. Run the following query in osqueryi:
`SELECT * FROM gatekeeper;`

### What did you expect to see?

expected to see `assessments_enabled` set to 0

### What did you see instead?

I saw that both `assessments_enabled` and `dev_id_enabled` are set to 1.

### PR DESCRIPTION
**Pull request by thierryfranzetti**
Since macOS 15, location of files containing gatekeeper configuration changed (although their content seems to be the same). This commit accounts for the various locations, depending on the OS version.

With this commit, on macOS 15+:

- `assessments_enabled` and `dev_id_enabled` columns now contain correct values. They were previously always set to '1' (error case) even if gatekeeper was disabled ;
- `version` column is now filled in. It was previously left empty.

Tests were performed on macOS 14, macOS15 and macOS 26.

This commit should also make table `gatekeeper_approved_apps` be populated correctly on macOS 15+. I was not able to test because gatekeeper approved apps can no more be easily added.

Fixes #8528

### CODE REVIEW

File: osquery/tables/system/darwin/gatekeeper.cpp [hunk 1]
```diff
@@ -22,19 +22,40 @@ namespace fs = boost::filesystem;
...
+  auto os_version = SQL::selectAllFrom("os_version");
+  if (os_version.size() != 1) {
+    return false;
+  }
+
+  try {
+    version = std::stoi(os_version.front().at("major"));
+    return true;
+  } catch (const std::exception&) {
+  }
```
Comment (zwass) [inline osquery/tables/system/darwin/gatekeeper.cpp]: Please prefer `tryTo<int>`

**Review by zwass — CHANGES_REQUESTED** [review]
Generally looking good, but one code style request. I triggered CI which needs to be done manually for first-time contributors.

Thank you!

File: osquery/tables/system/darwin/gatekeeper.cpp [hunk 2]
```diff
@@ -16,25 +16,47 @@
...
 const std::string kGkeOpaquePath =
     "/var/db/gkopaque.bundle/Contents/version.plist";
 
-const std::string kPolicyDb = "/var/db/SystemPolicy";
+const std::string kLegacyPolicyDb = "/var/db/SystemPolicy";
+const std::string kPolicyDb = "/var/db/SystemPolicyConfiguration/SystemPolicy";
 
-bool isGateKeeperDevIdEnabled() {
+static bool getMajorOSVersion(int& version) {
+  auto os_version = SQL::selectAllFrom("os_version");
```
Comment (directionless) [inline osquery/tables/system/darwin/gatekeeper.cpp:42]: Using `SQL::selectAllFrom` is a bit of an antipattern -- it's part of a mess that makes the test binaries linked into a huge blob. 

I tend to favor just trying to use the data -- In this case, can we see if the newer file exists and uses that?

If we really need the version API, I'd pull the implementation from somewhere into a helper. I think os_version is `osquery/tables/system/darwin/os_version.mm:39-193`

Comment (thierryfranzetti) [reply osquery/tables/system/darwin/gatekeeper.cpp:42]: For the correctness of the solution, I'd prefer using the OS version and target the appropriate files.
One could plant a file on macOS 14 and older to make osquery return the wrong values. I agree this would require being root, so likely outside the threat model of osquery anyway.

In order to break dependency on `SQL::selectAllFrom`, I can add a function in `os_version.mm` that checks if the operating system is at least of a specific version (same as `isBigSurOrHigher` in `osquery/tables/networking/darwin/wifi.mm` but in a generic way).

```
bool isOperatingSystemAtLeastVersion(int majorVersion, int minorVersion, int patchVersion) {
  NSProcessInfo* processInfo = [NSProcessInfo processInfo];
  NSOperatingSystemVersion min_version = {majorVersion, minorVersion, patchVersion};

  return [processInfo isOperatingSystemAtLeastVersion:(min_version)];
}
```

Let me know if this would be OK for you or if you decide data-driven pattern is definitely preferred.

File: osquery/tables/system/darwin/gatekeeper.cpp (hunk 1 above)
Comment (thierryfranzetti) [reply osquery/tables/system/darwin/gatekeeper.cpp]: Done

File: osquery/tables/system/darwin/gatekeeper.cpp (hunk 2 above)
Comment (zwass) [reply osquery/tables/system/darwin/gatekeeper.cpp:42]: That objc approach sgtm, @directionless does that work for you?

Comment (zwass) [reply osquery/tables/system/darwin/gatekeeper.cpp]: @thierryfranzetti please feel free to proceed. I'd love to get this into the release.

Comment (thierryfranzetti) [reply osquery/tables/system/darwin/gatekeeper.cpp]: @zwass Submitted !

**Review by zwass — APPROVED** [review]
LGTM thank you!
