### PR TITLE
Fix autoloaded extension processes outliving the main process

### LINKED ISSUE #4358: Fix autoloaded extension processes outliving the main process
When osqueryd is killed the extensions are not automatically killed, if the process comes back up quickly enough the extension will register with the new process which might cause problems like the refuse to register duplicated extension we're seeing in prod. This might also cause some annoyance with osqueryi.

### PR DESCRIPTION
**Pull request by SAlexandru**
Fix #4358
Added a custom stop function to WatcherRunner to stop all autoloaded extensions, before shutting down. Also, modified PlatformProcess for posix  to send SIGTERM, and not SIGINT (keyboard interrupt) when trying to nicely kill a process.
Run osqueryi locally and checked that after it completes no more Unix socket error messages appear.
Also,  runned an instance of osqueryd and running a simple query with osqueryi. Made sure that osqueryi doesn't kill any process that osqueryd has started.

### CODE REVIEW

**Comment by obelisk** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 0acaf888ed293ea8c8bd8137eafc26e8fefa103c (Job results: [3476](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3476/)) failed the code audit or documentation test.

**Comment by osqueryer** [comment]
:no_good: The commit 08db84854a6929bb3bd563ba452369767d6f4603 (Job results: [3482](https://jenkins.osquery.io/job/osqueryPullRequestAudit/3482/)) failed the code audit or documentation test.

File: osquery/core/posix/process.cpp [hunk 1]
```diff
@@ -59,7 +59,7 @@ bool PlatformProcess::killGracefully() const {
     return false;
   }
 
-  int status = ::kill(nativeHandle(), SIGINT);
+  int status = ::kill(nativeHandle(), SIGTERM);
```
Comment (theopolis) [inline osquery/core/posix/process.cpp]: This method should 'ask nicely', if `SIGTERM` causes a crash on macOS or Linux then we should keep `SIGINT`.

Comment (theopolis) [reply osquery/core/posix/process.cpp]: I tested and this is fine :)

File: osquery/main/main.cpp [hunk 2]
```diff
@@ -140,6 +140,7 @@ int startShell(osquery::Initializer& runner, int argc, char* argv[]) {
     retcode = osquery::launchIntoShell(argc, argv);
     // Finally shutdown.
     runner.requestShutdown();
```
Comment (fmanco) [inline osquery/main/main.cpp]: Any reason why we don't need to call `runner.requestShutdown()` on the `startDaemon()` version?

File: osquery/main/main.cpp [hunk 3]
```diff
@@ -140,6 +140,7 @@ int startShell(osquery::Initializer& runner, int argc, char* argv[]) {
...
+    runner.waitForShutdown();
```
Comment (fmanco) [inline osquery/main/main.cpp]: Do you actually need this here? because I `requestShutdown()` already calls `waitShutdown()`. I actually think `requestShutdown()` shouldn't do it because of semantics but just raising the point.

**Comment by fmanco** [comment]
I'm not 100% this is completely working. I tested on Linux, and it looks like some threads are not outliving the extensions and still trying to connect to them. This is still much better than the current scenario but we should take a look before merging.

```
$ strace -f -efork,vfork,clone,exit,execve ./osqueryi --line 'select version from osquery_info'
execve("./osqueryi", ["./osqueryi", "--line", "select version from osquery_info"], [/* 49 vars */]) = 0
clone(child_stack=0x7f8b5b40f2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5b4139d0, tls=0x7f8b5b413700, child_tidptr=0x7f8b5b4139d0) = 1292766
strace: Process 1292766 attached
[pid 1292765] clone(child_stack=0x7f8b5ac0e2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5ac129d0, tls=0x7f8b5ac12700, child_tidptr=0x7f8b5ac129d0) = 1292767
strace: Process 1292767 attached
[pid 1292765] clone(child_stack=0x7f8b5a40d2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5a4119d0, tls=0x7f8b5a411700, child_tidptr=0x7f8b5a4119d0) = 1292768
strace: Process 1292768 attached
[pid 1292765] clone(child_stack=0x7f8b59c0c2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b59c109d0, tls=0x7f8b59c10700, child_tidptr=0x7f8b59c109d0) = 1292769
strace: Process 1292769 attached
[pid 1292766] clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f8b5b4139d0) = 1292770
strace: Process 1292770 attached
[pid 1292770] execve("/usr/lib/osquery/extensions/fb_osquery.ext", ["/usr/lib/osquery/extensions/fb_o"..., "--socket", "/home/fmanco/.osquery/shell.em", "--timeout", "3", "--interval", "3"], [/* 50 vars */]) = 0
[pid 1292770] clone(child_stack=0x7f83b59fbcb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f83b59ff9d0, tls=0x7f83b59ff700, child_tidptr=0x7f83b59ff9d0) = 1292771
strace: Process 1292771 attached
[pid 1292769] clone(child_stack=0x7f8b62c2c2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b62c309d0, tls=0x7f8b62c30700, child_tidptr=0x7f8b62c309d0) = 1292772
strace: Process 1292772 attached
[pid 1292772] exit(0)                   = ?
[pid 1292772] +++ exited with 0 +++
[pid 1292769] clone(child_stack=0x7f8b5940b2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5940f9d0, tls=0x7f8b5940f700, child_tidptr=0x7f8b5940f9d0) = 1292773
strace: Process 1292773 attached
[pid 1292773] exit(0)                   = ?
[pid 1292773] +++ exited with 0 +++
[pid 1292769] clone(strace: Process 1292774 attached
child_stack=0x7f8b62c2c2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b62c309d0, tls=0x7f8b62c30700, child_tidptr=0x7f8b62c309d0) = 1292774
[pid 1292770] clone(strace: Process 1292775 attached
child_stack=0x7f83ae892cb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f83ae8969d0, tls=0x7f83ae896700, child_tidptr=0x7f83ae8969d0) = 1292775
[pid 1292774] exit(0)                   = ?
[pid 1292774] +++ exited with 0 +++
[pid 1292769] clone(strace: Process 1292776 attached
child_stack=0x7f8b5940b2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5940f9d0, tls=0x7f8b5940f700, child_tidptr=0x7f8b5940f9d0) = 1292776
[pid 1292769] clone(child_stack=0x7f8b5930a2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5930e9d0, tls=0x7f8b5930e700, child_tidptr=0x7f8b5930e9d0) = 1292777
strace: Process 1292777 attached
[pid 1292776] exit(0)                   = ?
[pid 1292776] +++ exited with 0 +++
[pid 1292769] clone(strace: Process 1292778 attached
child_stack=0x7f8b62c2c2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b62c309d0, tls=0x7f8b62c30700, child_tidptr=0x7f8b62c309d0) = 1292778
[pid 1292777] exit(0)                   = ?
[pid 1292777] +++ exited with 0 +++
[pid 1292769] clone(strace: Process 1292779 attached
child_stack=0x7f8b5940b2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5940f9d0, tls=0x7f8b5940f700, child_tidptr=0x7f8b5940f9d0) = 1292779
[pid 1292779] exit(0)                   = ?
[pid 1292779] +++ exited with 0 +++
[pid 1292769] clone(strace: Process 1292780 attached
child_stack=0x7f8b5930a2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5930e9d0, tls=0x7f8b5930e700, child_tidptr=0x7f8b5930e9d0) = 1292780
[pid 1292780] exit(0)                   = ?
[pid 1292780] +++ exited with 0 +++
[pid 1292769] clone(child_stack=0x7f8b5940b2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5940f9d0, tls=0x7f8b5940f700, child_tidptr=0x7f8b5940f9d0) = 1292781
strace: Process 1292781 attached
[pid 1292781] exit(0)                   = ?
[pid 1292781] +++ exited with 0 +++
[pid 1292769] clone(strace: Process 1292782 attached
child_stack=0x7f8b5930a2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5930e9d0, tls=0x7f8b5930e700, child_tidptr=0x7f8b5930e9d0) = 1292782
[pid 1292782] exit(0)                   = ?
[pid 1292782] +++ exited with 0 +++
[pid 1292778] exit(0)                   = ?
[pid 1292778] +++ exited with 0 +++
[pid 1292770] clone(strace: Process 1292783 attached
child_stack=0x7f83ae091cb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f83ae0959d0, tls=0x7f83ae095700, child_tidptr=0x7f83ae0959d0) = 1292783
[pid 1292769] clone(strace: Process 1292784 attached
child_stack=0x7f8b5930a2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5930e9d0, tls=0x7f8b5930e700, child_tidptr=0x7f8b5930e9d0) = 1292784
[pid 1292784] exit(0)                   = ?
[pid 1292784] +++ exited with 0 +++
[pid 1292769] clone(strace: Process 1292785 attached
child_stack=0x7f8b62c2c2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b62c309d0, tls=0x7f8b62c30700, child_tidptr=0x7f8b62c309d0) = 1292785
[pid 1292785] exit(0)                   = ?
[pid 1292785] +++ exited with 0 +++
[pid 1292783] clone(child_stack=0x7f83b968bcb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f83b968f9d0, tls=0x7f83b968f700, child_tidptr=0x7f83b968f9d0) = 1292786
strace: Process 1292786 attached
[pid 1292786] exit(0)                   = ?
[pid 1292786] +++ exited with 0 +++
[pid 1292783] clone(strace: Process 1292787 attached
child_stack=0x7f83b968bcb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f83b968f9d0, tls=0x7f83b968f700, child_tidptr=0x7f83b968f9d0) = 1292787
[pid 1292787] exit(0)                   = ?
[pid 1292787] +++ exited with 0 +++
[pid 1292769] clone(strace: Process 1292788 attached
child_stack=0x7f8b5930a2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b5930e9d0, tls=0x7f8b5930e700, child_tidptr=0x7f8b5930e9d0) = 1292788
[pid 1292788] exit(0)                   = ?
[pid 1292788] +++ exited with 0 +++
[pid 1292769] clone(strace: Process 1292789 attached
child_stack=0x7f8b62c2c2f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8b62c309d0, tls=0x7f8b62c30700, child_tidptr=0x7f8b62c309d0) = 1292789
[pid 1292789] exit(0)                   = ?
[pid 1292789] +++ exited with 0 +++
version = 3.2.4-24-g93475b538
[pid 1292770] --- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=1292765, si_uid=0} ---
[pid 1292775] exit(0)                   = ?
[pid 1292775] +++ exited with 0 +++
[pid 1292783] exit(0)                   = ?
[pid 1292783] +++ exited with 0 +++
[pid 1292771] +++ exited with 143 +++
[pid 1292770] +++ exited with 143 +++
[pid 1292766] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1292770, si_uid=0, si_status=143, si_utime=0, si_stime=1} ---
[pid 1292766] exit(0)                   = ?
[pid 1292767] exit(0)                   = ?
[pid 1292766] +++ exited with 0 +++
[pid 1292767] +++ exited with 0 +++
[pid 1292769] exit(0)                   = ?
[pid 1292769] +++ exited with 0 +++
Thrift: Fri May  4 04:48:56 2018 TSocket::open() connect() <Host:  Port: 0>No such file or directory
[pid 1292768] exit(0)                   = ?
[pid 1292768] +++ exited with 0 +++
+++ exited with 0 +++
```

```
$ ./osqueryi --verbose --line 'select version from osquery_info
I0504 04:50:58.163604 1300172 init.cpp:390] osquery initialized [version=3.2.4-24-g93475b538]
I0504 04:50:58.163651 1300172 init.cpp:397] Using default flagfile: /etc/osquery/osquery.flags.default
I0504 04:50:58.163769 1300172 extensions.cpp:389] Found autoloadable extension: /usr/lib/osquery/extensions/fb_osquery.ext
I0504 04:50:58.164057 1300210 interface.cpp:263] Extension manager service starting: /home/fmanco/.osquery/shell.em
I0504 04:50:58.164358 1300206 watcher.cpp:603] Created and monitoring extension child (1300212): /usr/lib/osquery/extensions/fb_osquery.ext
V0504 04:50:58.176321 1300212 init.cpp:383] osquery extension initialized [sdk=2.3.4]
V0504 04:50:58.176393 1300212 init.cpp:387] Using default flagfile: /etc/osquery/osquery.flags.default
I0504 04:50:58.177403 1300280 interface.cpp:104] Registering extension (fb_osquery, 59019, version=1.0.4, sdk=2.3.4)
I0504 04:50:58.177445 1300280 registry.cpp:458] Extension 59019 registered config plugin configerator
I0504 04:50:58.177459 1300280 registry.cpp:458] Extension 59019 registered distributed plugin fbinternal
I0504 04:50:58.177469 1300280 registry.cpp:458] Extension 59019 registered logger plugin scribe
I0504 04:50:58.193217 1300280 registry.cpp:458] Extension 59019 registered table plugin fb_devserver_groups
I0504 04:50:58.193250 1300280 registry.cpp:458] Extension 59019 registered table plugin fb_devserver_owners
I0504 04:50:58.193256 1300280 registry.cpp:458] Extension 59019 registered table plugin fb_smc_tiers
I0504 04:50:58.193260 1300280 registry.cpp:458] Extension 59019 registered table plugin fb_tw_tasks
I0504 04:50:58.193264 1300280 registry.cpp:458] Extension 59019 registered table plugin fb_whoami
V0504 04:50:58.194752 1300212 extensions.cpp:513] Extension (fb_osquery, 59019, 1.0.4, 2.3.4) registered
V0504 04:50:58.194865 1300371 interface.cpp:295] Extension service starting: /home/fmanco/.osquery/shell.em.59019
I0504 04:50:58.205531 1300172 init.cpp:663] Error reading config: config file does not exist: /etc/osquery/osquery.conf
I0504 04:50:58.205590 1300172 events.cpp:1079] Error registering subscriber: process_file_events: Subscriber disabled via configuration
version = 3.2.4-24-g93475b538
Thrift: Fri May  4 04:50:58 2018 TSocket::open() connect() <Host:  Port: 0>No such file or directory
I0504 04:50:58.406956 1300209 extensions.cpp:217] Extension UUID 59019 shutdown request failed
```
