### PR TITLE
Increase the limit on systemd unit iteration

### LINKED ISSUE #8680: 1000 systemd unit limit is way too low
On my regular desktop system running a couple of containers, desktop applications and other services I have 300+ units known to systemd.

But, if an ephemeral service starts and then enters the failed state - and a notable example is Ubuntu apport crashes - then that unit enters the systemd unit table permanently until `systemctl reset-failed` is run (which no one ever does normally, but particularly on a desktop).

This limit here is absurdly low in that context:

https://github.com/osquery/osquery/blob/e4ff72ee0b88e3101ad36cc6328d4634fab7f483/osquery/tables/system/linux/dbus/methods/listunitsmethodhandler.cpp#L16-L17

But worse, the failure scenario when it's exceeded is ridiculous: the table just stops counting at 1000.

Two things need fixing here: (1) come up with a limit which doesn't sit under normal usage of 30% of the maximum. A reasonable number would be `131070`: 2*65535, aka 2* the maximum number of network ports available. While there's no specific reason this number couldn't be exceeded, a system having 2* the number of processes in it's systemd unit table as it's possible to have network ports on the system would be quite exceptional.

(2) _sort_ the output when the table size is exceeded: if a choice has to be made, including *failed* units in the table is much, _much_ less important then including running units. And within failed units, failed units are more important then failed instantiated units - i.e. parameterized units.

### PR DESCRIPTION
**Pull request by directionless**
Fixes #8680

It sounds like we're still nervous removing the limit completely -- Since some systemd units can be user created, it provides a theoretical route to crashing osquery. (See [discussion](https://github.com/osquery/osquery/pull/8802#discussion_r2994498087) on this PR)

So instead., this greatly increases the limit, and emits a warning if we hit it.

### CODE REVIEW

File: osquery/tables/system/linux/dbus/methods/listunitsmethodhandler.cpp [hunk 1]
```diff
@@ -11,13 +11,6 @@
 
 namespace osquery {
 
-namespace {
-
-// Make sure we have an upper limit so we don't risk infinite loops
-const std::size_t kMaxSystemdUnitCount{1000U};
```
Comment (directionless) [inline osquery/tables/system/linux/dbus/methods/listunitsmethodhandler.cpp:17]: @alessandrogario I think this limit came from y'all in https://github.com/osquery/osquery/pull/6562#discussion_r524528715 Do you think we really need it?

Comment (alessandrogario) [reply osquery/tables/system/linux/dbus/methods/listunitsmethodhandler.cpp:17]: I seem to recall I was worried about user-controlled startup items potentially causing osquery to spin indefinitely (or at least, for a long time).

In this case it would be units in the user session; not many distributions enabled this by default last time I checked, but Fedora for example did (and they are really useful!).

I have not checked out the code yet, but I think this was an arbitrary high ceiling. Maybe it could be increased 10x or 20x rather than removed completely?

Comment (zwass) [reply osquery/tables/system/linux/dbus/methods/listunitsmethodhandler.cpp:17]: I'm personally open to removing the limit entirely. I think there are plenty of places where a user could generate a ton of data and it's not clear to me this one would be made significantly worse by osquery potentially retrieving it (in comparison to the impact it may have on systemd or other system resources).

I don't feel strongly though.

Comment (directionless) [reply osquery/tables/system/linux/dbus/methods/listunitsmethodhandler.cpp:17]: The AI robots assert the dbus stuff buffers it into ram anyhow, so we can't totally eliminate it. 

But I could 100x it if we wanted to be really risk adverse. 

Mostly though, I feel unconcerned. Users creating a lot of units is an interesting case. With a limit, it would act to hide important data. Without a limit it potentially consumes a lot of ram. Not sure which is better

Comment (zwass) [reply osquery/tables/system/linux/dbus/methods/listunitsmethodhandler.cpp:17]: As I think about it more, with this sort of resource consumption issue seems like at least we have the watchdog as a backstop?

Comment (alessandrogario) [reply osquery/tables/system/linux/dbus/methods/listunitsmethodhandler.cpp:17]: Here are some of my general thoughts on the matter, not specifically targeting this PR.

I think that most times when presented with such problems I find myself wondering: can this be used to disable osquery?

It is good that we have the watchdog, but if you can reliably trigger it via resource exhaustion (or causing extensive query delays) then it effectively becomes a primitive to make endpoints disappear from telemetry to hide your tracks.

The answer, I think, depends on your use case: is it for detection, or is it for inventory? Using a high ceiling is kind of way to not choose one of the other on behalf of the users.

I'm not against removing the limit if you all feel like it's the best choice here

Comment (directionless) [reply osquery/tables/system/linux/dbus/methods/listunitsmethodhandler.cpp:17]: Yah. those are good points. But also, that flooding systemd will inevitably cause some important things to get missed. 

So maybe the answer is to (a) up the max 100x and (b) emit an error if we hit it.

Comment (directionless) [reply osquery/tables/system/linux/dbus/methods/listunitsmethodhandler.cpp:17]: Okay, do we like this more?

Comment (alessandrogario) [reply osquery/tables/system/linux/dbus/methods/listunitsmethodhandler.cpp:17]: I think this is a great approach!
