### PR TITLE
Detect disk encryption status on macOS 10.13 High Sierra

### LINKED ISSUE #3709: macOS 10.13 disk encryption table shows incorrect results when using APFS
The implementation of `filevault` has changed with APFS on 10.13, causing the `disk_encryption` table to display inacurate results. 

```
osquery> select * from disk_encryption;
+--------------+--------------------------------------+-----------+------+-----+-----------+
| name         | uuid                                 | encrypted | type | uid | user_uuid |
+--------------+--------------------------------------+-----------+------+-----+-----------+
| /dev/disk0   |                                      | 0         |      |     |           |
| /dev/disk0s1 | E5E04863-018E-4456-BBC6-651B8CD62E3F | 0         |      |     |           |
| /dev/disk0s2 | 53AA9CD1-739F-4145-AF46-531E4C82823B | 0         |      |     |           |
| /dev/disk0s3 | 7D901236-4A13-41BC-809D-BD479755B170 | 0         |      |     |           |
| /dev/disk1   | A2CCE967-487F-435B-B852-37521ACD797B | 0         |      |     |           |
| /dev/disk1s1 | 331EB8D9-5D26-3D90-AD71-A3A4F784BAB9 | 0         |      |     |           |
| /dev/disk1s2 | 6FD23F05-83B7-4B8E-BC16-93A34337CE1E | 0         |      |     |           |
| /dev/disk1s3 | CFA25C98-A1CE-4F3C-945F-62F8B1E8477B | 0         |      |     |           |
| /dev/disk1s4 | 3C9956D6-1671-4546-8C51-8F4DF448AB1B | 0         |      |     |           |
+--------------+--------------------------------------+-----------+------+-----+-----------+
```

### PR DESCRIPTION
**Pull request by zwass**
PoC as of now.

Closes #3709

### CODE REVIEW

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 1]
```diff
@@ -130,33 +136,118 @@ void genFDEStatusForBSDName(const std::string& bsd_name,
...
+    // DMAPFS * apfs = [[DMAPFS alloc] initWithManager:man];
+    cls = NSClassFromString(@"DMAPFS");
+    sls = NSSelectorFromString(@"alloc");
+    id apfs = [cls performSelector:sls];
+    sls = NSSelectorFromString(@"initWithManager:");
+    [apfs performSelector:sls withObject:man];
+
+    DADiskRef targetVol = DADiskCreateFromBSDName(NULL, session, r["name"].c_str());
+
+    //err = [apfs isEncryptedVolume:targetVol encrypted:&isEncrypted];
```
Comment (zwass) [inline osquery/tables/system/darwin/disk_encryption.mm]: My research indicated that I had to use `NSInvocation` rather than `performSelector` when passing C types to the receiver. This also doesn't generate warnings from the compiler about possible memory leaks, but I don't know that it is actually any safer.

**Comment by zwass** [comment]
There is quite a bit of cleanup and refactoring that should be done before merging this, but I'd really like to get @theopolis feedback before proceeding further.

On my High Sierra machine, it does generate results consistent with `diskutil apfs list`.

File: osquery/tables/system/darwin/disk_encryption.mm (hunk 1 above)
Comment (zwass) [reply osquery/tables/system/darwin/disk_encryption.mm]: This is noted in the [documentation for performSelector](https://developer.apple.com/documentation/objectivec/1418956-nsobject/1418764-performselector):
> This method is the same as performSelector: except that you can supply an argument for aSelector. aSelector should identify a method that takes a single argument of type id. For methods with other argument types and return values, use NSInvocation.

Comment (zwass) [reply osquery/tables/system/darwin/disk_encryption.mm]: There may also be a possibility of wrapping with NSValue and using performSelector as described in (https://stackoverflow.com/a/1185566/491710) and other StackOverflow discussions.

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 2]
```diff
@@ -0,0 +1,299 @@
...
+    CFBundleLoadExecutable(bundle);
+
+    DASessionRef session = DASessionCreate(kCFAllocatorDefault);
+
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Warc-performSelector-leaks"
+    // DMManager *man = [DMManager sharedManager]
+    id cls = NSClassFromString(@"DMManager");
+    if (![cls respondsToSelector:@selector(sharedManager)]) {
+      LOG(ERROR) << "DMManager does not respond to sharedManager selector";
```
Comment (zwass) [inline osquery/tables/system/darwin/disk_encryption.mm]: I could use some advice as to how to structure the error handling here and below. We need to be careful to make the appropriate `CFRelease` calls depending on how many of the calls that perform initialization succeeded. We can't rely on ARC or RAII to do this cleanup (from what I can tell) because of the dynamic nature of the calls that are made.

Maybe something like the ScopeGuard with `std::function` pattern?

Comment (zwass) [reply osquery/tables/system/darwin/disk_encryption.mm]: [Background on ScopeGuard](https://stackoverflow.com/a/31365171/491710)

Comment (zwass) [reply osquery/tables/system/darwin/disk_encryption.mm]: @marpaia thinks I should do the appropriate releases manually in each location and leave a comment imploring future developers to beware. I'm inclined to agree so that we can move on.

Comment (zwass) [reply osquery/tables/system/darwin/disk_encryption.mm]: The PR is now updated to do error handling and manual cleanup.

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 3]
```diff
@@ -0,0 +1,347 @@
...
+      return;
+    }
+    [apfs performSelector:@selector(initWithManager:) withObject:man];
+
+#pragma clang diagnostic pop
+
+    DADiskRef targetVol = DADiskCreateFromBSDName(nullptr, session, r["name"].c_str());
+
+    // err = [apfs isEncryptedVolume:targetVol encrypted:&isEncrypted];
+    char *typeEncodings;
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]: Can you initialize to `nullptr`?

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 4]
```diff
@@ -0,0 +1,347 @@
...
+    asprintf(&typeEncodings,
+             "%s%s%s%s%s",
+             @encode(int), // return
+             @encode(id), // self
+             @encode(SEL), // _cmd
+             @encode(DADiskRef),
+             @encode(char*));
+    NSMethodSignature *signature = [NSMethodSignature signatureWithObjCTypes: typeEncodings];
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]: nit, ` ` after `signatureWithObjCTypes:`.

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 5]
```diff
@@ -0,0 +1,347 @@
...
+    }
+    [apfs performSelector:@selector(initWithManager:) withObject:man];
+
+#pragma clang diagnostic pop
+
+    DADiskRef targetVol = DADiskCreateFromBSDName(nullptr, session, r["name"].c_str());
+
+    // err = [apfs isEncryptedVolume:targetVol encrypted:&isEncrypted];
+    char *typeEncodings;
+    asprintf(&typeEncodings,
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]: Maybe check that `typeEncodings` is no longer a `nullptr` afterward?

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 6]
```diff
@@ -0,0 +1,347 @@
...
+      LOG(ERROR) << "Error calling cryptoUsersForVolume:users:";
+      return;
+    }
+
+    if (cryptoUsers != nullptr) {
+      @autoreleasepool {
+        for (NSString *userUUID in cryptoUsers) {
+          std::string uuidStr = std::string([userUUID UTF8String]);
+          if (kHardcodedDiskUUIDs.count(uuidStr) == 0) {
+            QueryData rows = SQL::selectAllFrom("users", "uuid", EQUALS, "foo");
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]: Need to use the returned `UUID`? Why `foo`?

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 7]
```diff
@@ -0,0 +1,347 @@
...
+
+    if (err != 0) {
+      LOG(ERROR) << "Error calling cryptoUsersForVolume:users:";
+      return;
+    }
+
+    if (cryptoUsers != nullptr) {
+      @autoreleasepool {
+        for (NSString *userUUID in cryptoUsers) {
+          std::string uuidStr = std::string([userUUID UTF8String]);
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]: If this is a `nullptr` then `std::string` will throw.

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 8]
```diff
@@ -0,0 +1,347 @@
...
+    CFRelease(bundle);
+
+    if (err != 0) {
+      LOG(ERROR) << "Error calling cryptoUsersForVolume:users:";
+      return;
+    }
+
+    if (cryptoUsers != nullptr) {
+      @autoreleasepool {
+        for (NSString *userUUID in cryptoUsers) {
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]: Are you sure these are `NSString`s? Should you iterate them as `id` and check if their `NSType` is `NSString` for safety?

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 9]
```diff
@@ -0,0 +1,347 @@
...
+             @encode(DADiskRef),
+             @encode(char*));
+    NSMethodSignature *signature = [NSMethodSignature signatureWithObjCTypes: typeEncodings];
+    free(typeEncodings);
+
+    char isEncrypted = 1;
+    char *isEncryptedPtr = &isEncrypted;
+    int err = 0;
+
+    NSInvocation *inv = [NSInvocation invocationWithMethodSignature:signature];
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]: Should you apply checks to the value in `signature` before using it?

Comment (theopolis) [reply osquery/tables/system/darwin/disk_encryption.mm]: I've not seen `NSInvocation` before, what sort of checks should we apply to make sure we're not going to throw or otherwise do bad things?

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 10]
```diff
@@ -0,0 +1,347 @@
...
+    [inv setSelector:@selector(isEncryptedVolume:encrypted:)];
+    [inv setReturnValue:&err];
+    [inv setArgument:&targetVol atIndex:2];
+    [inv setArgument:&isEncryptedPtr atIndex:3];
+    [inv invokeWithTarget:apfs];
+    if (targetVol == nullptr) {
+      LOG(ERROR)
+          << "Error calling isEncryptedVolume:encrypted:, targetVol is null";
+      CFRelease((__bridge CFTypeRef)apfs);
+      CFRelease(session);
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]: Maybe this series of releases and unloading can be wrapped into a reusable lambda?

**Comment by zwass** [comment]
I was able to substantially clean up the cleanup handling in error cases by using `std::function` and a lambda as @theopolis suggested.

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 11]
```diff
@@ -0,0 +1,347 @@
...
+    LOG(ERROR) << "Error creating DiskArbitration session";
+    CFBundleUnloadExecutable(bundle);
+    CFRelease(bundle);
+    return;
+  }
+
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Warc-performSelector-leaks"
+    // DMManager *man = [DMManager sharedManager]
+    id cls = NSClassFromString(@"DMManager");
```
[the remark this answers is not in the document]
Comment (zwass) [reply osquery/tables/system/darwin/disk_encryption.mm]: done

File: osquery/tables/system/darwin/disk_encryption.mm (hunk 9 above)
Comment (zwass) [reply osquery/tables/system/darwin/disk_encryption.mm]: I am now checking that `signature` is not null. I'm not sure what other checks should be applied with NSInvocation... The docs (https://developer.apple.com/documentation/foundation/nsinvocation) do not mention anything about it throwing, but I'm definitely no expert with this mac stuff.

**Comment by zwass** [comment]
```
$ ./tools/analysis/profile.py --leaks --config leaks.conf
Analyzing leaks in query: SELECT * FROM disk_encryption;
  definitely: 0 leaks for 0 total leaked bytes.
```

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 12]
```diff
@@ -0,0 +1,408 @@
...
+      cleanup();
+      return;
+    }
+    SEL sel = @selector(sharedManager);
+    if (![cls respondsToSelector:sel]) {
+      LOG(ERROR) << "DMManager does not respond to sharedManager selector";
+      cleanup();
+      return;
+    }
+    id man = [cls performSelector:sel];
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]: Check for `nullptr` here.

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 13]
```diff
@@ -0,0 +1,408 @@
...
+    cleanup = [&]() {
+      CFRelease((__bridge CFTypeRef)apfs);
+      CFRelease(session);
+      CFBundleUnloadExecutable(bundle);
+      CFRelease(bundle);
+    };
+
+#pragma clang diagnostic pop
+
+    DADiskRef targetVol = DADiskCreateFromBSDName(nullptr, session, r["name"].c_str());
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]: Could this return a `nullptr`?

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 14]
```diff
@@ -0,0 +1,408 @@
...
+    }
+    signature = [NSMethodSignature signatureWithObjCTypes:typeEncodings];
+    free(typeEncodings);
+    if (signature == nullptr) {
+      LOG(ERROR) << "Got null NSMethodSignature";
+      cleanup();
+      return;
+    }
+
+    NSArray *cryptoUsers;
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]: Initialize to `nullptr`.

File: osquery/tables/system/darwin/disk_encryption.mm [hunk 15]
```diff
@@ -0,0 +1,408 @@
...
+        for (id arrObj in cryptoUsers) {
+          if (![arrObj isKindOfClass:[NSString class]]) {
+            continue;
+          }
+
+          const char* cStr = [(NSString*)arrObj UTF8String];
+          if (cStr == nullptr) {
+            continue;
+          }
+          std::string uuidStr = std::string(cStr);
```
Comment (theopolis) [inline osquery/tables/system/darwin/disk_encryption.mm]:
```
std::string uuidStr(cStr);
```

**Comment by zwass** [comment]
I had colleagues verify that osquery returns the same results on macOS 10.12 machines, and that it returns the appropriate results on macOS 10.13 machines.

File: osquery/tables/system/darwin/disk_encryption.mm (hunk 12 above)
Comment (zwass) [reply osquery/tables/system/darwin/disk_encryption.mm]: done

File: osquery/tables/system/darwin/disk_encryption.mm (hunk 13 above)
Comment (zwass) [reply osquery/tables/system/darwin/disk_encryption.mm]: done

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
:no_good: The commit 16bbc68f70e33d5f6f78ffd4f28b262047622c7f (Job results: [2589](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2589/)) failed the code audit or documentation test.
