### PR TITLE
fix regular files being tagged as symlinks

### LINKED ISSUE #4578: file incorrectly checking symbolic links
file table is incorrectly returning files are symbolic links when they are regular files. On inspection of the code, the following line is incorrect:

https://github.com/facebook/osquery/blob/f6d077cbf7e1f60eef06ccdaf568f25971d178e9/osquery/tables/utility/file.cpp#L57

I'm pretty certain it should instead be
```cpp
  if ((link_stat.st_mode & S_IFLNK) == S_IFLNK) {
```

### PR DESCRIPTION
**Pull request by mchaffe**
Closes #4578 

Fixes logic according to https://www.gnu.org/software/libc/manual/html_node/Testing-File-Type.html

### CODE REVIEW

**Comment by mkareta** [comment]
ok to test

File: osquery/tables/utility/file.cpp [hunk 1]
```diff
@@ -54,7 +54,7 @@ void genFileInfo(const fs::path& path,
     // Path was not real, had too may links, or could not be accessed.
     return;
   }
-  if ((link_stat.st_mode & S_IFLNK) != 0) {
+  if ((link_stat.st_mode & S_IFLNK) == S_IFLNK) {
```
Comment (fmanco) [inline osquery/tables/utility/file.cpp]: nit: this should work but can we use S_ISLNK() macro instead?

Comment (mchaffe) [reply osquery/tables/utility/file.cpp]: It looks like it was using S_ISLNK() but was changed in this PR https://github.com/facebook/osquery/pull/2286

**Comment by fmanco** [comment]
jenkins test audit
jenkins test windows

**Comment by fmanco** [comment]
jenkins test audit

**Comment by fmanco** [comment]
jenkins test windows

**Comment by fmanco** [comment]
jenkins test windows

**Comment by theopolis** [comment]
jenkins test windows
