### PR TITLE
Fix CI: Remove Login Items plist support from startup_items table

### LINKED ISSUE #8718: StartupItemsTests fails after macOS update
This is causing CI failures:

```
24: [----------] 1 test from StartupItemsTests
24: [ RUN      ] StartupItemsTests.test_parse_startup_items
24: /Users/runner/work/osquery/osquery/workspace/src/osquery/tables/system/tests/darwin/startup_items_tests.cpp:37: Failure
24: Value of: boost::starts_with( results[0]["path"], "/Applications/iTunes.app/Contents/MacOS/iTunesHelper.app")
24:   Actual: false
24: Expected: true
24: 
24: /Users/runner/work/osquery/osquery/workspace/src/osquery/tables/system/tests/darwin/startup_items_tests.cpp:41: Failure
24: Value of: boost::starts_with(results[1]["path"], "/private/tmp/this_does_not_exist")
24:   Actual: false
24: Expected: true
24: 
24: [  FAILED  ] StartupItemsTests.test_parse_startup_items (6 ms)
```

https://github.com/osquery/osquery/actions/runs/19528506761/job/55906067029#step:19:1119
https://github.com/osquery/osquery/actions/runs/19457185100/job/55673314196#step:19:1118

On my development machine the test was passing, then I installed the latest security update (15.7.2) and the test started failing without rebuilding any files.

It looks like Apple may have made some changes to the format of plist files.

### PR DESCRIPTION
**Pull request by zwass**
Fixes #8718

Remove support for parsing Login Items from com.apple.loginitems.plist, keeping only traditional StartupItems from /System/Library/StartupItems/ and /Library/StartupItems/ directories.

This was causing CI failures after recent macOS updates (15.7.2), seemingly due to changes in plist parsing APIs. The functionality seems to be no longer supported, see
https://forums.macrumors.com/threads/lost-login-items.2073306/?post=25193038#post-25193038 https://eclecticlight.co/2022/06/21/how-helpers-are-changing-in-ventura/

### CODE REVIEW

File: osquery/tables/system/darwin/startup_items.cpp [hunk 1]
```diff
@@ -13,25 +13,15 @@
...
 
 namespace osquery {
 namespace tables {
 
 const std::vector<std::string> kLibraryStartupItemPaths = {
-    "/System/Library/StartupItems/", "/Library/StartupItems/",
-};
-
-// Path (after /Users/foo) where the login items plist will be found
-const std::string kLoginItemsPlistPath =
```
Comment (directionless) [inline osquery/tables/system/darwin/startup_items.cpp:29]: Hrm....

Reading the ElecticLight post, it talks about `~/Library/Application Support/com.apple.backgroundtaskmanagementagent/backgrounditems.btm` which still exists on my machine, but the internet says maybe old. 

Internet also says things are moving to `/private/var/db/com.apple.backgroundtaskmanagement/BackgroundItems-v*.btm` I have 3 versions, and it's not clear to me which is used. 

Given our general target of older OSes, I wonder if it makes sense to leave this in, and make it parse whatever file paths we fine?

Comment (directionless) [reply osquery/tables/system/darwin/startup_items.cpp:29]: Oh, I see https://github.com/osquery/osquery/pull/8726 now. Let me review that

**Review by directionless — APPROVED** [review]
I'm not sure why we need this and 8726 -- this seems to be editing files 8726 simply removes. But I'm willing to approve it

**Comment by zwass** [comment]
In #8726 the startup_items.cpp file is renamed to startup_files.mm (and edited).
