### PR TITLE
[Fix #3756] Fixing windows hashes table

### LINKED ISSUE #3756: Windows osqueryi: hash table returning inconsistent values
OS: Win10
Osquery Version: 2.8.0

I noticed today that the hash table in osquery was returning inconsistent results:

**Example:** Hashing a single file:
`select path, sha256 from hash where path="C:\windows\system32\calc.exe";`
Repro steps: Run the above query multiple times, observe that the hash value changes with each query:
```
osquery> select path, sha256 from hash where path="C:\windows\system32\calc.exe";
+------------------------------+------------------------------------------------------------------+
| path                         | sha256                                                           |
+------------------------------+------------------------------------------------------------------+
| C:\windows\system32\calc.exe | c4337e09c6ee8625065dcdfeac56f099345a2bb329813f227718b45e1f7f04a0 |
+------------------------------+------------------------------------------------------------------+
osquery> select path, sha256 from hash where path="C:\windows\system32\calc.exe";
+------------------------------+------------------------------------------------------------------+
| path                         | sha256                                                           |
+------------------------------+------------------------------------------------------------------+
| C:\windows\system32\calc.exe | b093fd472121cda0bbb1e0079479de36325f1b2faa7fda54c4f757565572fe1d |
+------------------------------+------------------------------------------------------------------+
osquery> select path, sha256 from hash where path="C:\windows\system32\calc.exe";
+------------------------------+------------------------------------------------------------------+
| path                         | sha256                                                           |
+------------------------------+------------------------------------------------------------------+
| C:\windows\system32\calc.exe | b093fd472121cda0bbb1e0079479de36325f1b2faa7fda54c4f757565572fe1d |
+------------------------------+------------------------------------------------------------------+
```

In the event that you are not able to repro the above (it seems to be intermittent), this query reliably reproduces if run multiple times in succession:
`select path, sha256 from hash where path="C:\windows\system32\sethc.exe" OR path="c:\windows\system32\utilman.exe" OR path="c:\windows\system32\osk.exe" OR path="c:\windows\system32\narrorator.exe" OR path="c:\windows\system32\magnify.exe" OR path="c:\windows\system32\displayswitch.exe";`

### PR DESCRIPTION
**Pull request by muffins**
One windows systems, using the `readFile` without setting the `block` mode `true` results in the use of Windows Async file reads. These can be advantageous for incredibly large files, but in the situation of reading a file for hashing purposes we prefer blocking operations to ensure we get all of the data at once.

This addresses #3756 by ensuring that we have read all of the data before hashing.

### CODE REVIEW

**Comment by muffins** [comment]
Test output:
```
C:\Users\thor\work\repos\osquery [master ≡]
λ  osqueryi
Using a virtual database. Need help, type '.help'
osquery> .mode line
osquery> select md5 from hash where path = 'C:\Users\thor\Desktop\osqueryi.exe'
    ...> ;
  md5 = 08397c9b2274a7ffa7419eaeb09f1072
osquery> select md5 from hash where path = 'C:\Users\thor\Desktop\osqueryi.exe';
  md5 = 08397c9b2274a7ffa7419eaeb09f1072
osquery> select md5 from hash where path = 'C:\Users\thor\Desktop\osqueryi.exe';
  md5 = 08397c9b2274a7ffa7419eaeb09f1072
osquery> select md5 from hash where path = 'C:\Users\thor\Desktop\osqueryi.exe';
  md5 = 08397c9b2274a7ffa7419eaeb09f1072
osquery> select md5 from hash where path = 'C:\Users\thor\Desktop\osqueryi.exe';
  md5 = 08397c9b2274a7ffa7419eaeb09f1072
osquery> select md5 from hash where path = 'C:\Users\thor\Desktop\osqueryi.exe';
  md5 = 08397c9b2274a7ffa7419eaeb09f1072
osquery> select md5 from hash where path = 'C:\Users\thor\Desktop\osqueryi.exe';
  md5 = 08397c9b2274a7ffa7419eaeb09f1072
osquery> select md5 from hash where path = 'C:\Windows\system32\calc.exe';
  md5 = 4673c27fdcab6166578a1863060d83ff
osquery> select md5 from hash where path = 'C:\Windows\system32\calc.exe';
  md5 = 4673c27fdcab6166578a1863060d83ff
osquery> select md5 from hash where path = 'C:\Windows\system32\calc.exe';
  md5 = 4673c27fdcab6166578a1863060d83ff
osquery> select md5 from hash where path = 'C:\Windows\system32\calc.exe';
  md5 = 4673c27fdcab6166578a1863060d83ff
osquery> select md5 from hash where path = 'C:\Windows\system32\calc.exe';
  md5 = 4673c27fdcab6166578a1863060d83ff
osquery> select md5 from hash where path = 'C:\Windows\system32\calc.exe';
  md5 = 4673c27fdcab6166578a1863060d83ff
osquery> select md5 from hash where path = 'C:\Windows\system32\calc.exe';
  md5 = 4673c27fdcab6166578a1863060d83ff
```

File: osquery/tables/system/hash.cpp [hunk 1]
```diff
@@ -108,7 +108,8 @@ MultiHashes hashMultiFromFile(int mask, const std::string& path) {
                           hash.second->update(&buffer[0], size);
                         }
                       }
-                    }));
+                    }),
+                    true);
```
Comment (theopolis) [inline osquery/tables/system/hash.cpp]: How did you find this?

Comment (muffins) [reply osquery/tables/system/hash.cpp]: This was just looking at our implementation (for Windows, I verified that it _should_ be alright on Linux through tests and verifying `O_NONBLOCK` wasn't going to have issues on linux), for where we make the Windows Async file reads - as I knew this was something we had implemented, and found that we set "open blocking" to `false` by default. On Windows this causes us to use the async file reads, which can happen out of band of the main thread of operation, and occasionally your data can be delivered late. Setting this to `true` ensures we don't open the file with asynchronous reading turned on on Windows.

Comment (theopolis) [reply osquery/tables/system/hash.cpp]: I’m worried that user controlled sockets can DoS the daemon with blocking opens.
