### PR TITLE
[Fix #3527] Addressing interface indexing in arp_cache table

### LINKED ISSUE #3527: windows: Crashes querying against arp_cache table
Queries against the Windows `arp_cache` table are currently causing crashes. Will update with more details as I get them. Unsure of which versions this affects, but it's at least 2.6.0

### PR DESCRIPTION
**Pull request by muffins**
The `arp_cache` table wasn't grabbing indexes correctly, and thus we were hitting scenarios where attempts to get an interface at a predefined index wouldn't exist.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 01cb4873de7c85c8a387a0be9dc48a5436afa78b (Job results: [1539](https://jenkins.osquery.io/job/osqueryPullRequestOSX/1539/)) failed one or more tests (**macOS/OS X**).

File: osquery/tables/networking/windows/arp_cache.cpp [hunk 1]
```diff
@@ -43,10 +40,10 @@ const std::map<unsigned char, const std::string> kMapOfState = {
 
 QueryData genIPv4ArpCache(QueryContext& context) {
   QueryData results;
-  QueryData interfaces = genInterfaceDetails(context);
+  auto interfaces = genInterfaceDetails(context);
```
Comment (obelisk) [inline osquery/tables/networking/windows/arp_cache.cpp]: 👍

File: osquery/tables/networking/windows/arp_cache.cpp [hunk 2]
```diff
@@ -59,27 +56,33 @@ QueryData genIPv4ArpCache(QueryContext& context) {
     long interfaceIndex;
     if (iface.count("interface") > 0) {
       safeStrtol(iface.at("interface"), 10, interfaceIndex);
-      std::string macAddress = iface.at("mac");
-
+      auto macAddress = iface.count("mac") > 0 ? iface.at("mac") : "";
       mapOfInterfaces.insert(std::make_pair(interfaceIndex, macAddress));
```
Comment (obelisk) [inline osquery/tables/networking/windows/arp_cache.cpp]: Does `mapOfInterfaces[interfaceIndex] = iface.count("mac") > 0 ? iface.at("mac") : "";` not work

File: osquery/tables/networking/windows/interfaces.cpp [hunk 3]
```diff
@@ -37,12 +37,11 @@ void genInterfaceDetail(const WmiResultItem& adapter, QueryData& results) {
   std::vector<std::string> vPlaceHolder;
   unsigned __int64 ulPlaceHolder;
 
-  r["interface"] = INTEGER(lPlaceHolder);
   adapter.GetString("MACAddress", r["mac"]);
   adapter.GetString("AdapterType", r["type"]);
-
   adapter.GetString("Description", r["description"]);
   adapter.GetLong("InterfaceIndex", lPlaceHolder);
+  r["interface"] = INTEGER(lPlaceHolder);
```
Comment (obelisk) [inline osquery/tables/networking/windows/interfaces.cpp]: Interface has type [TEXT](https://github.com/facebook/osquery/blob/master/specs/arp_cache.table#L6)

**Comment by osqueryer** [comment]
:no_good: The commit 09b27852584052cf5473af96a536f49786209016 (Job results: [2155](https://jenkins.osquery.io/job/osqueryPullRequestAudit/2155/)) failed the code audit or documentation test.
