### PR TITLE
[Fix #852] Use a user-specific temporary dir for shell state

### LINKED ISSUE #852: Move osqueryi state to ~/.osquery/
If multiple uses act on /tmp/osquery unhandled  permissions problems will lead to unexpected behavior.

### PR DESCRIPTION
**Pull request by theopolis**

### CODE REVIEW

**Comment by theopolis** [comment]
ok to test

File: osquery/main/shell.cpp [hunk 1]
```diff
@@ -17,15 +19,27 @@
...
-    osquery::FLAGS_disable_logging = true;
+  osquery::FLAGS_disable_logging = true;
+  if (osquery::pathExists(homedir).ok() ||
+      boost::filesystem::create_directory(homedir)) {
+    osquery::FLAGS_database_path = homedir + "/shell.db";
+    osquery::FLAGS_extensions_socket = homedir + "/shell.em";
+  } else {
+    LOG(ERROR) << "Cannot create osquery work directory: " << homedir;
+    return 1;
   }
```
Comment (marpaia) [inline osquery/main/shell.cpp]: Do you think it's worth doing this in `runner` if it's called with `osquery::OSQUERY_TOOL_SHELL`?

Comment (theopolis) [inline osquery/main/shell.cpp]: That's a great idea!
