### PR TITLE
[Fix #3079] Change users table to query from registry instead of WMI

### LINKED ISSUE #3079: windows: Users table is currently hanging with special user account types
Selecting anything from the users table is currently hanging. I did a stack trace on this and it looks to be an issue somewhere in the WMI implementation. Currently investigating if this impacts other WMI tables.
```
C:\Users\thor\work\repos\osquery [master ≡]> .\build\windows10\osquery\Release\osqueryi.exe
Using a virtual database. Need help, type '.help'
osquery> select * from users;
```

### PR DESCRIPTION
**Pull request by poppyseedplehzr**
This changes the functionality of the users virtual table to query the system registry for Roaming Profiles specifically, as opposed to the WMI database.

### CODE REVIEW

**Comment by osqueryer** [comment]
:-1: The commit 01c3ebf62f2e945cdd8ccdf1bc5ca444aeae6fc5 (Job results: [4295](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4295/)) failed one or more tests (**Linux**).

**Comment by osqueryer** [comment]
:-1: The commit 01c3ebf62f2e945cdd8ccdf1bc5ca444aeae6fc5 (Job results: [4296](https://jenkins.osquery.io/job/osqueryPullRequestLinux/4296/)) failed one or more tests (**Linux**).

File: osquery/tables/system/windows/users.cpp [hunk 1]
```diff
@@ -29,40 +30,48 @@ std::string psidToString(PSID sid);
...
-  WmiRequest accntReq(
-      "select Description, Name from Win32_UserAccount where sid = \"" +
-      r["uuid"] + "\"");
-  auto& accntResults = accntReq.results();
-  if (accntReq.getStatus().ok() && !accntResults.empty()) {
-    accntResults[0].GetString("Description", r["description"]);
-    accntResults[0].GetString("Name", r["username"]);
-  } else {
+void processRoamingProfiles(const std::set<std::string>& processedSids,
+                            QueryData& results) {
```
Comment (ryanheffernan) [inline osquery/tables/system/windows/users.cpp]: processedSids is never used, is this intentional?

File: osquery/tables/system/windows/users.cpp [hunk 2]
```diff
@@ -160,21 +162,11 @@ void processWinLocalAccounts(const std::set<std::string>& processedSids,
...
-    return results;
-  }
-  auto& wmiResults = req.results();
   std::set<std::string> processedSids;
 
-  for (const auto& res : wmiResults) {
-    ProcessWinProfile(res, processedSids, results);
-  }
+  processLocalAccounts(processedSids, results);
+  processRoamingProfiles(processedSids, results);
```
Comment (ryanheffernan) [inline osquery/tables/system/windows/users.cpp]: ditto. processedSids is populated by processLocalAccounts but then never used

File: osquery/tables/system/windows/users.cpp [hunk 3]
```diff
@@ -29,40 +30,48 @@ std::string psidToString(PSID sid);
...
+    Row r;
+    if (profile.at("type") != "subkey") {
+      continue;
+    }
+    auto sidString = profile.at("name");
+    r["uuid"] = sidString;
+
+    QueryData profileDetails;
+    queryKey(
+        kRegProfilePath + kRegSep + sidString + kRegSep + "ProfileImagePath",
```
Comment (ryanheffernan) [inline osquery/tables/system/windows/users.cpp]: I don't think this will return data, since ProfileImagePath is a reg value and not a key. Being able to infer this and do the appropriate reg query in queryKeys is tbd.
```
osquery> select * from registry where key = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\S-1-5-80-1511743022-2277352901-878227523-1247458543-3245048236\ProfileImagePath';
osquery> select * from registry where key = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\S-1-5-80-1511743022-2277352901-878227523-1247458543-3245048236' and name = 'ProfileImagePath';
+--------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+---------------+-------------------------------+------------+
| key
                                                     | path

                                   | name             | type          | data
              | mtime      |
+--------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+---------------+-------------------------------+------------+
| HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\S-1-5-80-1511743022-2277352901-878227523-1247458543-3245048236 | HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\S-1-5-80-1511743022-2277352901-878227523-1247458543-3245048236\ProfileImagePath | ProfileImagePath | REG_EXPAND_SZ | C:\Users\HiveStreamingService | 1490043999 |
+--------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+---------------+-------------------------------+------------+
```
You could do the following, or just execute something like the above SQL to get the data.
```
queryKey(profile.at("path") + kRegSep, profileDetails);
r["LocalPath"] = "";
for (const auto& det: profileDetails) {
  if (det["name"] == "ProfileImagePath") {
    r["LocalPath"] = det["data"];
  }
} 
```
