### PR TITLE
[Fix #1063] Allow configure-time symlink resolution in FSEvents

### LINKED ISSUE #1063: Mac system symlinked directories don't work with file_changes
On a Mac, when subscribing to file_changes on a symlinked directory, (such as `/etc` which actually is `/private/etc` on osx), osquery appears to hook the directory but doesn't report any changes.  This functionality may also be the same in the linux version too - but I haven't tested it.  

### To reproduce:

1) Use a config like this:
```json
{
  "schedule": {
    "file_changes": {
      "query": "select * from file_changes;",
      "interval": 10
    }
  },
  "file_paths": {
    "users": [
      "/Users/me/Desktop/%%"
    ],
    "all_etc": [
      "/etc/%%"
    ],
    "tmp": [
      "/tmp/%%"
    ]
  }
}
```

2) and start `osqueryd` with that config.  Observe a successful listener addition in the osqueryd log: 
```
I0427 22:39:46.991005 1955668736 file_changes.cpp:59] Added listener to: /etc
I0427 22:39:46.991032 1955668736 file_changes.cpp:59] Added listener to: /tmp
I0427 22:39:46.991052 1955668736 file_changes.cpp:59] Added listener to: /Users/me/Desktop
```

3) See events in osqueryd.results.log for `/Users/me/Desktop` but not for `/etc/

4) Repeat with `/private/etc/%%` as the path to monitor instead of `/etc/%%`, and observe the file changes work.

### Possible fixes

If resolving symlinks is not an option, perhaps it would be useful to throw an error to the user indicating that a file_paths config is effectively disabled when pointed at a symlink.
 
Perhaps exposing a configurable "follow_symlinks" option may also be useful too.  Following symlinks has its own security implications too, so it may be useful to implement this to be configurable per-path in the config.

### PR DESCRIPTION
**Pull request by theopolis**
When osqueryd loads it can use symlinks to subscribe for `file_events` assuming those symlinks are constant. Here "configure time" means the initialization of the daemon after it reads a config and knows about the set of paths it should watch. This helps for the `/etc` -> `/private/etc` case.

### CODE REVIEW

File: osquery/events/darwin/fsevents.cpp [hunk 1]
```diff
@@ -117,9 +120,19 @@ void FSEventsEventPublisher::tearDown() {
...
   // Rebuild the watch paths.
   paths_.clear();
-  for (const auto& subscription : subscriptions_) {
-    auto fs_subscription = getSubscriptionContext(subscription->context);
-    paths_.insert(fs_subscription->path);
+  for (auto& subscription : subscriptions_) {
+    auto sub = getSubscriptionContext(subscription->context);
+    // Check if the requested path was a symlink at configure time.
+    boost::system::error_code ec;
+    if (fs::is_symlink(sub->path, ec)) {
```
Comment (theopolis) [inline osquery/events/darwin/fsevents.cpp]: This should be a loop with a max = 5 number of iterations.

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test

**Comment by theopolis** [comment]
ok to test
